name: Bug 报告 | Bug Report
description: 反馈软件缺陷或异常 | Report a bug to help us improve
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        感谢你的反馈！请详细填写以下内容，便于我们定位问题。
        Thank you for your feedback! Please fill out the following information to help us locate the issue.
  - type: input
    id: version
    attributes:
      label: 软件版本 | App Version
      description: 可在设置中的“关于”界面查看 | You can find it on the "About" interface in the settings
      placeholder: 例如 v1.2.3 | e.g. v1.2.3
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: 操作系统及版本 | OS & Version
      placeholder: 例如 Windows 10 22H2 64位 | e.g. Windows 10 22H2 64bit
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: 问题描述 | Description
      description: 简要描述遇到的问题 | Briefly describe the problem
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: 复现步骤 | Steps to Reproduce
      description: 如何复现该问题？如有必要可附截图/录屏 | How to reproduce this bug? Screenshots/recordings if needed
      placeholder: |
        1. 
        2. 
        3. 
    validations:
      required: false
  - type: textarea
    id: expected
    attributes:
      label: 期望结果 | Expected Behavior
      description: 你期望的正确行为或结果 | What did you expect to happen?
    validations:
      required: false
  - type: textarea
    id: extra
    attributes:
      label: 其他补充信息 | Additional Info
      description: 其他相关信息（如日志、配置、特殊环境等）| Any other context, logs, configs, special environment, etc.
    validations:
      required: false
