name: 功能请求 | Feature Request
description: 提出你对本项目的功能建议 | Suggest an idea for this project
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        感谢你的建议！请详细描述你的需求。
        Thank you for your suggestion! Please describe your needs in detail.
  - type: textarea
    id: description
    attributes:
      label: 功能描述 | Description
      description: 请描述你希望添加的功能 | Describe the feature you want
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: 需求动机 | Motivation
      description: 为什么需要这个功能？| Why do you need this feature?
    validations:
      required: true
  - type: textarea
    id: design
    attributes:
      label: 期望设计 | Expected Design
      description: （可选）描述或画出你期望的界面或交互 | (Optional) Describe or sketch the expected UI/UX
    validations:
      required: false
  - type: textarea
    id: extra
    attributes:
      label: 其他补充信息 | Additional Info
      description: 其他补充说明或建议 | Any other context or suggestions
    validations:
      required: false
